//create user
POST http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
    "name":"Тестовый пользователь",
    "about":"О себе",
    "avatar":"https://www.mirf.ru/wp-content/uploads/2015/09/maxresdefault16.jpg"
}

###
//get users
GET http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
//get user
GET http://localhost:3000/users/636c02b95ab4033298a04fea
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
